// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: entity_extension_data.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Spotify.Extendedmetadata.Proto {

  /// <summary>Holder for reflection information generated from entity_extension_data.proto</summary>
  public static partial class EntityExtensionDataReflection {

    #region Descriptor
    /// <summary>File descriptor for entity_extension_data.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static EntityExtensionDataReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChtlbnRpdHlfZXh0ZW5zaW9uX2RhdGEucHJvdG8SHnNwb3RpZnkuZXh0ZW5k",
            "ZWRtZXRhZGF0YS5wcm90bxoZZ29vZ2xlL3Byb3RvYnVmL2FueS5wcm90byKM",
            "AQoZRW50aXR5RXh0ZW5zaW9uRGF0YUhlYWRlchITCgtzdGF0dXNfY29kZRgB",
            "IAEoBRIMCgRldGFnGAIgASgJEg4KBmxvY2FsZRgDIAEoCRIcChRjYWNoZV90",
            "dGxfaW5fc2Vjb25kcxgEIAEoAxIeChZvZmZsaW5lX3R0bF9pbl9zZWNvbmRz",
            "GAUgASgDIqIBChNFbnRpdHlFeHRlbnNpb25EYXRhEkkKBmhlYWRlchgBIAEo",
            "CzI5LnNwb3RpZnkuZXh0ZW5kZWRtZXRhZGF0YS5wcm90by5FbnRpdHlFeHRl",
            "bnNpb25EYXRhSGVhZGVyEhIKCmVudGl0eV91cmkYAiABKAkSLAoOZXh0ZW5z",
            "aW9uX2RhdGEYAyABKAsyFC5nb29nbGUucHJvdG9idWYuQW55QiAKHGNvbS5z",
            "cG90aWZ5LmV4dGVuZGVkbWV0YWRhdGFIAg=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Google.Protobuf.WellKnownTypes.AnyReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Spotify.Extendedmetadata.Proto.EntityExtensionDataHeader), global::Spotify.Extendedmetadata.Proto.EntityExtensionDataHeader.Parser, new[]{ "StatusCode", "Etag", "Locale", "CacheTtlInSeconds", "OfflineTtlInSeconds" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Spotify.Extendedmetadata.Proto.EntityExtensionData), global::Spotify.Extendedmetadata.Proto.EntityExtensionData.Parser, new[]{ "Header", "EntityUri", "ExtensionData" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class EntityExtensionDataHeader : pb::IMessage<EntityExtensionDataHeader>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<EntityExtensionDataHeader> _parser = new pb::MessageParser<EntityExtensionDataHeader>(() => new EntityExtensionDataHeader());
    private pb::UnknownFieldSet _unknownFields;
    private int _hasBits0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<EntityExtensionDataHeader> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Spotify.Extendedmetadata.Proto.EntityExtensionDataReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public EntityExtensionDataHeader() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public EntityExtensionDataHeader(EntityExtensionDataHeader other) : this() {
      _hasBits0 = other._hasBits0;
      statusCode_ = other.statusCode_;
      etag_ = other.etag_;
      locale_ = other.locale_;
      cacheTtlInSeconds_ = other.cacheTtlInSeconds_;
      offlineTtlInSeconds_ = other.offlineTtlInSeconds_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public EntityExtensionDataHeader Clone() {
      return new EntityExtensionDataHeader(this);
    }

    /// <summary>Field number for the "status_code" field.</summary>
    public const int StatusCodeFieldNumber = 1;
    private readonly static int StatusCodeDefaultValue = 0;

    private int statusCode_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int StatusCode {
      get { if ((_hasBits0 & 1) != 0) { return statusCode_; } else { return StatusCodeDefaultValue; } }
      set {
        _hasBits0 |= 1;
        statusCode_ = value;
      }
    }
    /// <summary>Gets whether the "status_code" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool HasStatusCode {
      get { return (_hasBits0 & 1) != 0; }
    }
    /// <summary>Clears the value of the "status_code" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void ClearStatusCode() {
      _hasBits0 &= ~1;
    }

    /// <summary>Field number for the "etag" field.</summary>
    public const int EtagFieldNumber = 2;
    private readonly static string EtagDefaultValue = "";

    private string etag_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Etag {
      get { return etag_ ?? EtagDefaultValue; }
      set {
        etag_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }
    /// <summary>Gets whether the "etag" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool HasEtag {
      get { return etag_ != null; }
    }
    /// <summary>Clears the value of the "etag" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void ClearEtag() {
      etag_ = null;
    }

    /// <summary>Field number for the "locale" field.</summary>
    public const int LocaleFieldNumber = 3;
    private readonly static string LocaleDefaultValue = "";

    private string locale_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Locale {
      get { return locale_ ?? LocaleDefaultValue; }
      set {
        locale_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }
    /// <summary>Gets whether the "locale" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool HasLocale {
      get { return locale_ != null; }
    }
    /// <summary>Clears the value of the "locale" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void ClearLocale() {
      locale_ = null;
    }

    /// <summary>Field number for the "cache_ttl_in_seconds" field.</summary>
    public const int CacheTtlInSecondsFieldNumber = 4;
    private readonly static long CacheTtlInSecondsDefaultValue = 0L;

    private long cacheTtlInSeconds_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long CacheTtlInSeconds {
      get { if ((_hasBits0 & 2) != 0) { return cacheTtlInSeconds_; } else { return CacheTtlInSecondsDefaultValue; } }
      set {
        _hasBits0 |= 2;
        cacheTtlInSeconds_ = value;
      }
    }
    /// <summary>Gets whether the "cache_ttl_in_seconds" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool HasCacheTtlInSeconds {
      get { return (_hasBits0 & 2) != 0; }
    }
    /// <summary>Clears the value of the "cache_ttl_in_seconds" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void ClearCacheTtlInSeconds() {
      _hasBits0 &= ~2;
    }

    /// <summary>Field number for the "offline_ttl_in_seconds" field.</summary>
    public const int OfflineTtlInSecondsFieldNumber = 5;
    private readonly static long OfflineTtlInSecondsDefaultValue = 0L;

    private long offlineTtlInSeconds_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long OfflineTtlInSeconds {
      get { if ((_hasBits0 & 4) != 0) { return offlineTtlInSeconds_; } else { return OfflineTtlInSecondsDefaultValue; } }
      set {
        _hasBits0 |= 4;
        offlineTtlInSeconds_ = value;
      }
    }
    /// <summary>Gets whether the "offline_ttl_in_seconds" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool HasOfflineTtlInSeconds {
      get { return (_hasBits0 & 4) != 0; }
    }
    /// <summary>Clears the value of the "offline_ttl_in_seconds" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void ClearOfflineTtlInSeconds() {
      _hasBits0 &= ~4;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as EntityExtensionDataHeader);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(EntityExtensionDataHeader other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (StatusCode != other.StatusCode) return false;
      if (Etag != other.Etag) return false;
      if (Locale != other.Locale) return false;
      if (CacheTtlInSeconds != other.CacheTtlInSeconds) return false;
      if (OfflineTtlInSeconds != other.OfflineTtlInSeconds) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (HasStatusCode) hash ^= StatusCode.GetHashCode();
      if (HasEtag) hash ^= Etag.GetHashCode();
      if (HasLocale) hash ^= Locale.GetHashCode();
      if (HasCacheTtlInSeconds) hash ^= CacheTtlInSeconds.GetHashCode();
      if (HasOfflineTtlInSeconds) hash ^= OfflineTtlInSeconds.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (HasStatusCode) {
        output.WriteRawTag(8);
        output.WriteInt32(StatusCode);
      }
      if (HasEtag) {
        output.WriteRawTag(18);
        output.WriteString(Etag);
      }
      if (HasLocale) {
        output.WriteRawTag(26);
        output.WriteString(Locale);
      }
      if (HasCacheTtlInSeconds) {
        output.WriteRawTag(32);
        output.WriteInt64(CacheTtlInSeconds);
      }
      if (HasOfflineTtlInSeconds) {
        output.WriteRawTag(40);
        output.WriteInt64(OfflineTtlInSeconds);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (HasStatusCode) {
        output.WriteRawTag(8);
        output.WriteInt32(StatusCode);
      }
      if (HasEtag) {
        output.WriteRawTag(18);
        output.WriteString(Etag);
      }
      if (HasLocale) {
        output.WriteRawTag(26);
        output.WriteString(Locale);
      }
      if (HasCacheTtlInSeconds) {
        output.WriteRawTag(32);
        output.WriteInt64(CacheTtlInSeconds);
      }
      if (HasOfflineTtlInSeconds) {
        output.WriteRawTag(40);
        output.WriteInt64(OfflineTtlInSeconds);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (HasStatusCode) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(StatusCode);
      }
      if (HasEtag) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Etag);
      }
      if (HasLocale) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Locale);
      }
      if (HasCacheTtlInSeconds) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(CacheTtlInSeconds);
      }
      if (HasOfflineTtlInSeconds) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(OfflineTtlInSeconds);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(EntityExtensionDataHeader other) {
      if (other == null) {
        return;
      }
      if (other.HasStatusCode) {
        StatusCode = other.StatusCode;
      }
      if (other.HasEtag) {
        Etag = other.Etag;
      }
      if (other.HasLocale) {
        Locale = other.Locale;
      }
      if (other.HasCacheTtlInSeconds) {
        CacheTtlInSeconds = other.CacheTtlInSeconds;
      }
      if (other.HasOfflineTtlInSeconds) {
        OfflineTtlInSeconds = other.OfflineTtlInSeconds;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            StatusCode = input.ReadInt32();
            break;
          }
          case 18: {
            Etag = input.ReadString();
            break;
          }
          case 26: {
            Locale = input.ReadString();
            break;
          }
          case 32: {
            CacheTtlInSeconds = input.ReadInt64();
            break;
          }
          case 40: {
            OfflineTtlInSeconds = input.ReadInt64();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            StatusCode = input.ReadInt32();
            break;
          }
          case 18: {
            Etag = input.ReadString();
            break;
          }
          case 26: {
            Locale = input.ReadString();
            break;
          }
          case 32: {
            CacheTtlInSeconds = input.ReadInt64();
            break;
          }
          case 40: {
            OfflineTtlInSeconds = input.ReadInt64();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class EntityExtensionData : pb::IMessage<EntityExtensionData>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<EntityExtensionData> _parser = new pb::MessageParser<EntityExtensionData>(() => new EntityExtensionData());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<EntityExtensionData> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Spotify.Extendedmetadata.Proto.EntityExtensionDataReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public EntityExtensionData() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public EntityExtensionData(EntityExtensionData other) : this() {
      header_ = other.header_ != null ? other.header_.Clone() : null;
      entityUri_ = other.entityUri_;
      extensionData_ = other.extensionData_ != null ? other.extensionData_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public EntityExtensionData Clone() {
      return new EntityExtensionData(this);
    }

    /// <summary>Field number for the "header" field.</summary>
    public const int HeaderFieldNumber = 1;
    private global::Spotify.Extendedmetadata.Proto.EntityExtensionDataHeader header_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Spotify.Extendedmetadata.Proto.EntityExtensionDataHeader Header {
      get { return header_; }
      set {
        header_ = value;
      }
    }

    /// <summary>Field number for the "entity_uri" field.</summary>
    public const int EntityUriFieldNumber = 2;
    private readonly static string EntityUriDefaultValue = "";

    private string entityUri_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string EntityUri {
      get { return entityUri_ ?? EntityUriDefaultValue; }
      set {
        entityUri_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }
    /// <summary>Gets whether the "entity_uri" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool HasEntityUri {
      get { return entityUri_ != null; }
    }
    /// <summary>Clears the value of the "entity_uri" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void ClearEntityUri() {
      entityUri_ = null;
    }

    /// <summary>Field number for the "extension_data" field.</summary>
    public const int ExtensionDataFieldNumber = 3;
    private global::Google.Protobuf.WellKnownTypes.Any extensionData_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Google.Protobuf.WellKnownTypes.Any ExtensionData {
      get { return extensionData_; }
      set {
        extensionData_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as EntityExtensionData);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(EntityExtensionData other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Header, other.Header)) return false;
      if (EntityUri != other.EntityUri) return false;
      if (!object.Equals(ExtensionData, other.ExtensionData)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (header_ != null) hash ^= Header.GetHashCode();
      if (HasEntityUri) hash ^= EntityUri.GetHashCode();
      if (extensionData_ != null) hash ^= ExtensionData.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (header_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Header);
      }
      if (HasEntityUri) {
        output.WriteRawTag(18);
        output.WriteString(EntityUri);
      }
      if (extensionData_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(ExtensionData);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (header_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Header);
      }
      if (HasEntityUri) {
        output.WriteRawTag(18);
        output.WriteString(EntityUri);
      }
      if (extensionData_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(ExtensionData);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (header_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Header);
      }
      if (HasEntityUri) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(EntityUri);
      }
      if (extensionData_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(ExtensionData);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(EntityExtensionData other) {
      if (other == null) {
        return;
      }
      if (other.header_ != null) {
        if (header_ == null) {
          Header = new global::Spotify.Extendedmetadata.Proto.EntityExtensionDataHeader();
        }
        Header.MergeFrom(other.Header);
      }
      if (other.HasEntityUri) {
        EntityUri = other.EntityUri;
      }
      if (other.extensionData_ != null) {
        if (extensionData_ == null) {
          ExtensionData = new global::Google.Protobuf.WellKnownTypes.Any();
        }
        ExtensionData.MergeFrom(other.ExtensionData);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (header_ == null) {
              Header = new global::Spotify.Extendedmetadata.Proto.EntityExtensionDataHeader();
            }
            input.ReadMessage(Header);
            break;
          }
          case 18: {
            EntityUri = input.ReadString();
            break;
          }
          case 26: {
            if (extensionData_ == null) {
              ExtensionData = new global::Google.Protobuf.WellKnownTypes.Any();
            }
            input.ReadMessage(ExtensionData);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (header_ == null) {
              Header = new global::Spotify.Extendedmetadata.Proto.EntityExtensionDataHeader();
            }
            input.ReadMessage(Header);
            break;
          }
          case 18: {
            EntityUri = input.ReadString();
            break;
          }
          case 26: {
            if (extensionData_ == null) {
              ExtensionData = new global::Google.Protobuf.WellKnownTypes.Any();
            }
            input.ReadMessage(ExtensionData);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
