// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: extended_metadata.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Spotify.Extendedmetadata.Proto {

  /// <summary>Holder for reflection information generated from extended_metadata.proto</summary>
  public static partial class ExtendedMetadataReflection {

    #region Descriptor
    /// <summary>File descriptor for extended_metadata.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ExtendedMetadataReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChdleHRlbmRlZF9tZXRhZGF0YS5wcm90bxIec3BvdGlmeS5leHRlbmRlZG1l",
            "dGFkYXRhLnByb3RvGhRleHRlbnNpb25fa2luZC5wcm90bxobZW50aXR5X2V4",
            "dGVuc2lvbl9kYXRhLnByb3RvImUKDkV4dGVuc2lvblF1ZXJ5EkUKDmV4dGVu",
            "c2lvbl9raW5kGAEgASgOMi0uc3BvdGlmeS5leHRlbmRlZG1ldGFkYXRhLnBy",
            "b3RvLkV4dGVuc2lvbktpbmQSDAoEZXRhZxgCIAEoCSJiCg1FbnRpdHlSZXF1",
            "ZXN0EhIKCmVudGl0eV91cmkYASABKAkSPQoFcXVlcnkYAiADKAsyLi5zcG90",
            "aWZ5LmV4dGVuZGVkbWV0YWRhdGEucHJvdG8uRXh0ZW5zaW9uUXVlcnkiQAoa",
            "QmF0Y2hlZEVudGl0eVJlcXVlc3RIZWFkZXISDwoHY291bnRyeRgBIAEoCRIR",
            "CgljYXRhbG9ndWUYAiABKAkiqQEKFEJhdGNoZWRFbnRpdHlSZXF1ZXN0EkoK",
            "BmhlYWRlchgBIAEoCzI6LnNwb3RpZnkuZXh0ZW5kZWRtZXRhZGF0YS5wcm90",
            "by5CYXRjaGVkRW50aXR5UmVxdWVzdEhlYWRlchJFCg5lbnRpdHlfcmVxdWVz",
            "dBgCIAMoCzItLnNwb3RpZnkuZXh0ZW5kZWRtZXRhZGF0YS5wcm90by5FbnRp",
            "dHlSZXF1ZXN0In0KHkVudGl0eUV4dGVuc2lvbkRhdGFBcnJheUhlYWRlchId",
            "ChVwcm92aWRlcl9lcnJvcl9zdGF0dXMYASABKAUSHAoUY2FjaGVfdHRsX2lu",
            "X3NlY29uZHMYAiABKAMSHgoWb2ZmbGluZV90dGxfaW5fc2Vjb25kcxgDIAEo",
            "AyL+AQoYRW50aXR5RXh0ZW5zaW9uRGF0YUFycmF5Ek4KBmhlYWRlchgBIAEo",
            "CzI+LnNwb3RpZnkuZXh0ZW5kZWRtZXRhZGF0YS5wcm90by5FbnRpdHlFeHRl",
            "bnNpb25EYXRhQXJyYXlIZWFkZXISRQoOZXh0ZW5zaW9uX2tpbmQYAiABKA4y",
            "LS5zcG90aWZ5LmV4dGVuZGVkbWV0YWRhdGEucHJvdG8uRXh0ZW5zaW9uS2lu",
            "ZBJLCg5leHRlbnNpb25fZGF0YRgDIAMoCzIzLnNwb3RpZnkuZXh0ZW5kZWRt",
            "ZXRhZGF0YS5wcm90by5FbnRpdHlFeHRlbnNpb25EYXRhIiAKHkJhdGNoZWRF",
            "eHRlbnNpb25SZXNwb25zZUhlYWRlciK/AQoYQmF0Y2hlZEV4dGVuc2lvblJl",
            "c3BvbnNlEk4KBmhlYWRlchgBIAEoCzI+LnNwb3RpZnkuZXh0ZW5kZWRtZXRh",
            "ZGF0YS5wcm90by5CYXRjaGVkRXh0ZW5zaW9uUmVzcG9uc2VIZWFkZXISUwoR",
            "ZXh0ZW5kZWRfbWV0YWRhdGEYAiADKAsyOC5zcG90aWZ5LmV4dGVuZGVkbWV0",
            "YWRhdGEucHJvdG8uRW50aXR5RXh0ZW5zaW9uRGF0YUFycmF5QiAKHGNvbS5z",
            "cG90aWZ5LmV4dGVuZGVkbWV0YWRhdGFIAg=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Spotify.Extendedmetadata.Proto.ExtensionKindReflection.Descriptor, global::Spotify.Extendedmetadata.Proto.EntityExtensionDataReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Spotify.Extendedmetadata.Proto.ExtensionQuery), global::Spotify.Extendedmetadata.Proto.ExtensionQuery.Parser, new[]{ "ExtensionKind", "Etag" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Spotify.Extendedmetadata.Proto.EntityRequest), global::Spotify.Extendedmetadata.Proto.EntityRequest.Parser, new[]{ "EntityUri", "Query" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Spotify.Extendedmetadata.Proto.BatchedEntityRequestHeader), global::Spotify.Extendedmetadata.Proto.BatchedEntityRequestHeader.Parser, new[]{ "Country", "Catalogue" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Spotify.Extendedmetadata.Proto.BatchedEntityRequest), global::Spotify.Extendedmetadata.Proto.BatchedEntityRequest.Parser, new[]{ "Header", "EntityRequest" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Spotify.Extendedmetadata.Proto.EntityExtensionDataArrayHeader), global::Spotify.Extendedmetadata.Proto.EntityExtensionDataArrayHeader.Parser, new[]{ "ProviderErrorStatus", "CacheTtlInSeconds", "OfflineTtlInSeconds" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Spotify.Extendedmetadata.Proto.EntityExtensionDataArray), global::Spotify.Extendedmetadata.Proto.EntityExtensionDataArray.Parser, new[]{ "Header", "ExtensionKind", "ExtensionData" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Spotify.Extendedmetadata.Proto.BatchedExtensionResponseHeader), global::Spotify.Extendedmetadata.Proto.BatchedExtensionResponseHeader.Parser, null, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Spotify.Extendedmetadata.Proto.BatchedExtensionResponse), global::Spotify.Extendedmetadata.Proto.BatchedExtensionResponse.Parser, new[]{ "Header", "ExtendedMetadata" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class ExtensionQuery : pb::IMessage<ExtensionQuery>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ExtensionQuery> _parser = new pb::MessageParser<ExtensionQuery>(() => new ExtensionQuery());
    private pb::UnknownFieldSet _unknownFields;
    private int _hasBits0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<ExtensionQuery> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Spotify.Extendedmetadata.Proto.ExtendedMetadataReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ExtensionQuery() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ExtensionQuery(ExtensionQuery other) : this() {
      _hasBits0 = other._hasBits0;
      extensionKind_ = other.extensionKind_;
      etag_ = other.etag_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ExtensionQuery Clone() {
      return new ExtensionQuery(this);
    }

    /// <summary>Field number for the "extension_kind" field.</summary>
    public const int ExtensionKindFieldNumber = 1;
    private readonly static global::Spotify.Extendedmetadata.Proto.ExtensionKind ExtensionKindDefaultValue = global::Spotify.Extendedmetadata.Proto.ExtensionKind.UnknownExtension;

    private global::Spotify.Extendedmetadata.Proto.ExtensionKind extensionKind_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Spotify.Extendedmetadata.Proto.ExtensionKind ExtensionKind {
      get { if ((_hasBits0 & 1) != 0) { return extensionKind_; } else { return ExtensionKindDefaultValue; } }
      set {
        _hasBits0 |= 1;
        extensionKind_ = value;
      }
    }
    /// <summary>Gets whether the "extension_kind" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool HasExtensionKind {
      get { return (_hasBits0 & 1) != 0; }
    }
    /// <summary>Clears the value of the "extension_kind" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void ClearExtensionKind() {
      _hasBits0 &= ~1;
    }

    /// <summary>Field number for the "etag" field.</summary>
    public const int EtagFieldNumber = 2;
    private readonly static string EtagDefaultValue = "";

    private string etag_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Etag {
      get { return etag_ ?? EtagDefaultValue; }
      set {
        etag_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }
    /// <summary>Gets whether the "etag" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool HasEtag {
      get { return etag_ != null; }
    }
    /// <summary>Clears the value of the "etag" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void ClearEtag() {
      etag_ = null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as ExtensionQuery);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(ExtensionQuery other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (ExtensionKind != other.ExtensionKind) return false;
      if (Etag != other.Etag) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (HasExtensionKind) hash ^= ExtensionKind.GetHashCode();
      if (HasEtag) hash ^= Etag.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (HasExtensionKind) {
        output.WriteRawTag(8);
        output.WriteEnum((int) ExtensionKind);
      }
      if (HasEtag) {
        output.WriteRawTag(18);
        output.WriteString(Etag);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (HasExtensionKind) {
        output.WriteRawTag(8);
        output.WriteEnum((int) ExtensionKind);
      }
      if (HasEtag) {
        output.WriteRawTag(18);
        output.WriteString(Etag);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (HasExtensionKind) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) ExtensionKind);
      }
      if (HasEtag) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Etag);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(ExtensionQuery other) {
      if (other == null) {
        return;
      }
      if (other.HasExtensionKind) {
        ExtensionKind = other.ExtensionKind;
      }
      if (other.HasEtag) {
        Etag = other.Etag;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            ExtensionKind = (global::Spotify.Extendedmetadata.Proto.ExtensionKind) input.ReadEnum();
            break;
          }
          case 18: {
            Etag = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            ExtensionKind = (global::Spotify.Extendedmetadata.Proto.ExtensionKind) input.ReadEnum();
            break;
          }
          case 18: {
            Etag = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class EntityRequest : pb::IMessage<EntityRequest>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<EntityRequest> _parser = new pb::MessageParser<EntityRequest>(() => new EntityRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<EntityRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Spotify.Extendedmetadata.Proto.ExtendedMetadataReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public EntityRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public EntityRequest(EntityRequest other) : this() {
      entityUri_ = other.entityUri_;
      query_ = other.query_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public EntityRequest Clone() {
      return new EntityRequest(this);
    }

    /// <summary>Field number for the "entity_uri" field.</summary>
    public const int EntityUriFieldNumber = 1;
    private readonly static string EntityUriDefaultValue = "";

    private string entityUri_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string EntityUri {
      get { return entityUri_ ?? EntityUriDefaultValue; }
      set {
        entityUri_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }
    /// <summary>Gets whether the "entity_uri" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool HasEntityUri {
      get { return entityUri_ != null; }
    }
    /// <summary>Clears the value of the "entity_uri" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void ClearEntityUri() {
      entityUri_ = null;
    }

    /// <summary>Field number for the "query" field.</summary>
    public const int QueryFieldNumber = 2;
    private static readonly pb::FieldCodec<global::Spotify.Extendedmetadata.Proto.ExtensionQuery> _repeated_query_codec
        = pb::FieldCodec.ForMessage(18, global::Spotify.Extendedmetadata.Proto.ExtensionQuery.Parser);
    private readonly pbc::RepeatedField<global::Spotify.Extendedmetadata.Proto.ExtensionQuery> query_ = new pbc::RepeatedField<global::Spotify.Extendedmetadata.Proto.ExtensionQuery>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::Spotify.Extendedmetadata.Proto.ExtensionQuery> Query {
      get { return query_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as EntityRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(EntityRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (EntityUri != other.EntityUri) return false;
      if(!query_.Equals(other.query_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (HasEntityUri) hash ^= EntityUri.GetHashCode();
      hash ^= query_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (HasEntityUri) {
        output.WriteRawTag(10);
        output.WriteString(EntityUri);
      }
      query_.WriteTo(output, _repeated_query_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (HasEntityUri) {
        output.WriteRawTag(10);
        output.WriteString(EntityUri);
      }
      query_.WriteTo(ref output, _repeated_query_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (HasEntityUri) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(EntityUri);
      }
      size += query_.CalculateSize(_repeated_query_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(EntityRequest other) {
      if (other == null) {
        return;
      }
      if (other.HasEntityUri) {
        EntityUri = other.EntityUri;
      }
      query_.Add(other.query_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            EntityUri = input.ReadString();
            break;
          }
          case 18: {
            query_.AddEntriesFrom(input, _repeated_query_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            EntityUri = input.ReadString();
            break;
          }
          case 18: {
            query_.AddEntriesFrom(ref input, _repeated_query_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class BatchedEntityRequestHeader : pb::IMessage<BatchedEntityRequestHeader>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<BatchedEntityRequestHeader> _parser = new pb::MessageParser<BatchedEntityRequestHeader>(() => new BatchedEntityRequestHeader());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<BatchedEntityRequestHeader> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Spotify.Extendedmetadata.Proto.ExtendedMetadataReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public BatchedEntityRequestHeader() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public BatchedEntityRequestHeader(BatchedEntityRequestHeader other) : this() {
      country_ = other.country_;
      catalogue_ = other.catalogue_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public BatchedEntityRequestHeader Clone() {
      return new BatchedEntityRequestHeader(this);
    }

    /// <summary>Field number for the "country" field.</summary>
    public const int CountryFieldNumber = 1;
    private readonly static string CountryDefaultValue = "";

    private string country_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Country {
      get { return country_ ?? CountryDefaultValue; }
      set {
        country_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }
    /// <summary>Gets whether the "country" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool HasCountry {
      get { return country_ != null; }
    }
    /// <summary>Clears the value of the "country" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void ClearCountry() {
      country_ = null;
    }

    /// <summary>Field number for the "catalogue" field.</summary>
    public const int CatalogueFieldNumber = 2;
    private readonly static string CatalogueDefaultValue = "";

    private string catalogue_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Catalogue {
      get { return catalogue_ ?? CatalogueDefaultValue; }
      set {
        catalogue_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }
    /// <summary>Gets whether the "catalogue" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool HasCatalogue {
      get { return catalogue_ != null; }
    }
    /// <summary>Clears the value of the "catalogue" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void ClearCatalogue() {
      catalogue_ = null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as BatchedEntityRequestHeader);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(BatchedEntityRequestHeader other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Country != other.Country) return false;
      if (Catalogue != other.Catalogue) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (HasCountry) hash ^= Country.GetHashCode();
      if (HasCatalogue) hash ^= Catalogue.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (HasCountry) {
        output.WriteRawTag(10);
        output.WriteString(Country);
      }
      if (HasCatalogue) {
        output.WriteRawTag(18);
        output.WriteString(Catalogue);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (HasCountry) {
        output.WriteRawTag(10);
        output.WriteString(Country);
      }
      if (HasCatalogue) {
        output.WriteRawTag(18);
        output.WriteString(Catalogue);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (HasCountry) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Country);
      }
      if (HasCatalogue) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Catalogue);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(BatchedEntityRequestHeader other) {
      if (other == null) {
        return;
      }
      if (other.HasCountry) {
        Country = other.Country;
      }
      if (other.HasCatalogue) {
        Catalogue = other.Catalogue;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Country = input.ReadString();
            break;
          }
          case 18: {
            Catalogue = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Country = input.ReadString();
            break;
          }
          case 18: {
            Catalogue = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class BatchedEntityRequest : pb::IMessage<BatchedEntityRequest>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<BatchedEntityRequest> _parser = new pb::MessageParser<BatchedEntityRequest>(() => new BatchedEntityRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<BatchedEntityRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Spotify.Extendedmetadata.Proto.ExtendedMetadataReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public BatchedEntityRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public BatchedEntityRequest(BatchedEntityRequest other) : this() {
      header_ = other.header_ != null ? other.header_.Clone() : null;
      entityRequest_ = other.entityRequest_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public BatchedEntityRequest Clone() {
      return new BatchedEntityRequest(this);
    }

    /// <summary>Field number for the "header" field.</summary>
    public const int HeaderFieldNumber = 1;
    private global::Spotify.Extendedmetadata.Proto.BatchedEntityRequestHeader header_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Spotify.Extendedmetadata.Proto.BatchedEntityRequestHeader Header {
      get { return header_; }
      set {
        header_ = value;
      }
    }

    /// <summary>Field number for the "entity_request" field.</summary>
    public const int EntityRequestFieldNumber = 2;
    private static readonly pb::FieldCodec<global::Spotify.Extendedmetadata.Proto.EntityRequest> _repeated_entityRequest_codec
        = pb::FieldCodec.ForMessage(18, global::Spotify.Extendedmetadata.Proto.EntityRequest.Parser);
    private readonly pbc::RepeatedField<global::Spotify.Extendedmetadata.Proto.EntityRequest> entityRequest_ = new pbc::RepeatedField<global::Spotify.Extendedmetadata.Proto.EntityRequest>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::Spotify.Extendedmetadata.Proto.EntityRequest> EntityRequest {
      get { return entityRequest_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as BatchedEntityRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(BatchedEntityRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Header, other.Header)) return false;
      if(!entityRequest_.Equals(other.entityRequest_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (header_ != null) hash ^= Header.GetHashCode();
      hash ^= entityRequest_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (header_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Header);
      }
      entityRequest_.WriteTo(output, _repeated_entityRequest_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (header_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Header);
      }
      entityRequest_.WriteTo(ref output, _repeated_entityRequest_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (header_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Header);
      }
      size += entityRequest_.CalculateSize(_repeated_entityRequest_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(BatchedEntityRequest other) {
      if (other == null) {
        return;
      }
      if (other.header_ != null) {
        if (header_ == null) {
          Header = new global::Spotify.Extendedmetadata.Proto.BatchedEntityRequestHeader();
        }
        Header.MergeFrom(other.Header);
      }
      entityRequest_.Add(other.entityRequest_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (header_ == null) {
              Header = new global::Spotify.Extendedmetadata.Proto.BatchedEntityRequestHeader();
            }
            input.ReadMessage(Header);
            break;
          }
          case 18: {
            entityRequest_.AddEntriesFrom(input, _repeated_entityRequest_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (header_ == null) {
              Header = new global::Spotify.Extendedmetadata.Proto.BatchedEntityRequestHeader();
            }
            input.ReadMessage(Header);
            break;
          }
          case 18: {
            entityRequest_.AddEntriesFrom(ref input, _repeated_entityRequest_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class EntityExtensionDataArrayHeader : pb::IMessage<EntityExtensionDataArrayHeader>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<EntityExtensionDataArrayHeader> _parser = new pb::MessageParser<EntityExtensionDataArrayHeader>(() => new EntityExtensionDataArrayHeader());
    private pb::UnknownFieldSet _unknownFields;
    private int _hasBits0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<EntityExtensionDataArrayHeader> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Spotify.Extendedmetadata.Proto.ExtendedMetadataReflection.Descriptor.MessageTypes[4]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public EntityExtensionDataArrayHeader() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public EntityExtensionDataArrayHeader(EntityExtensionDataArrayHeader other) : this() {
      _hasBits0 = other._hasBits0;
      providerErrorStatus_ = other.providerErrorStatus_;
      cacheTtlInSeconds_ = other.cacheTtlInSeconds_;
      offlineTtlInSeconds_ = other.offlineTtlInSeconds_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public EntityExtensionDataArrayHeader Clone() {
      return new EntityExtensionDataArrayHeader(this);
    }

    /// <summary>Field number for the "provider_error_status" field.</summary>
    public const int ProviderErrorStatusFieldNumber = 1;
    private readonly static int ProviderErrorStatusDefaultValue = 0;

    private int providerErrorStatus_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int ProviderErrorStatus {
      get { if ((_hasBits0 & 1) != 0) { return providerErrorStatus_; } else { return ProviderErrorStatusDefaultValue; } }
      set {
        _hasBits0 |= 1;
        providerErrorStatus_ = value;
      }
    }
    /// <summary>Gets whether the "provider_error_status" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool HasProviderErrorStatus {
      get { return (_hasBits0 & 1) != 0; }
    }
    /// <summary>Clears the value of the "provider_error_status" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void ClearProviderErrorStatus() {
      _hasBits0 &= ~1;
    }

    /// <summary>Field number for the "cache_ttl_in_seconds" field.</summary>
    public const int CacheTtlInSecondsFieldNumber = 2;
    private readonly static long CacheTtlInSecondsDefaultValue = 0L;

    private long cacheTtlInSeconds_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long CacheTtlInSeconds {
      get { if ((_hasBits0 & 2) != 0) { return cacheTtlInSeconds_; } else { return CacheTtlInSecondsDefaultValue; } }
      set {
        _hasBits0 |= 2;
        cacheTtlInSeconds_ = value;
      }
    }
    /// <summary>Gets whether the "cache_ttl_in_seconds" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool HasCacheTtlInSeconds {
      get { return (_hasBits0 & 2) != 0; }
    }
    /// <summary>Clears the value of the "cache_ttl_in_seconds" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void ClearCacheTtlInSeconds() {
      _hasBits0 &= ~2;
    }

    /// <summary>Field number for the "offline_ttl_in_seconds" field.</summary>
    public const int OfflineTtlInSecondsFieldNumber = 3;
    private readonly static long OfflineTtlInSecondsDefaultValue = 0L;

    private long offlineTtlInSeconds_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long OfflineTtlInSeconds {
      get { if ((_hasBits0 & 4) != 0) { return offlineTtlInSeconds_; } else { return OfflineTtlInSecondsDefaultValue; } }
      set {
        _hasBits0 |= 4;
        offlineTtlInSeconds_ = value;
      }
    }
    /// <summary>Gets whether the "offline_ttl_in_seconds" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool HasOfflineTtlInSeconds {
      get { return (_hasBits0 & 4) != 0; }
    }
    /// <summary>Clears the value of the "offline_ttl_in_seconds" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void ClearOfflineTtlInSeconds() {
      _hasBits0 &= ~4;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as EntityExtensionDataArrayHeader);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(EntityExtensionDataArrayHeader other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (ProviderErrorStatus != other.ProviderErrorStatus) return false;
      if (CacheTtlInSeconds != other.CacheTtlInSeconds) return false;
      if (OfflineTtlInSeconds != other.OfflineTtlInSeconds) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (HasProviderErrorStatus) hash ^= ProviderErrorStatus.GetHashCode();
      if (HasCacheTtlInSeconds) hash ^= CacheTtlInSeconds.GetHashCode();
      if (HasOfflineTtlInSeconds) hash ^= OfflineTtlInSeconds.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (HasProviderErrorStatus) {
        output.WriteRawTag(8);
        output.WriteInt32(ProviderErrorStatus);
      }
      if (HasCacheTtlInSeconds) {
        output.WriteRawTag(16);
        output.WriteInt64(CacheTtlInSeconds);
      }
      if (HasOfflineTtlInSeconds) {
        output.WriteRawTag(24);
        output.WriteInt64(OfflineTtlInSeconds);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (HasProviderErrorStatus) {
        output.WriteRawTag(8);
        output.WriteInt32(ProviderErrorStatus);
      }
      if (HasCacheTtlInSeconds) {
        output.WriteRawTag(16);
        output.WriteInt64(CacheTtlInSeconds);
      }
      if (HasOfflineTtlInSeconds) {
        output.WriteRawTag(24);
        output.WriteInt64(OfflineTtlInSeconds);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (HasProviderErrorStatus) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(ProviderErrorStatus);
      }
      if (HasCacheTtlInSeconds) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(CacheTtlInSeconds);
      }
      if (HasOfflineTtlInSeconds) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(OfflineTtlInSeconds);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(EntityExtensionDataArrayHeader other) {
      if (other == null) {
        return;
      }
      if (other.HasProviderErrorStatus) {
        ProviderErrorStatus = other.ProviderErrorStatus;
      }
      if (other.HasCacheTtlInSeconds) {
        CacheTtlInSeconds = other.CacheTtlInSeconds;
      }
      if (other.HasOfflineTtlInSeconds) {
        OfflineTtlInSeconds = other.OfflineTtlInSeconds;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            ProviderErrorStatus = input.ReadInt32();
            break;
          }
          case 16: {
            CacheTtlInSeconds = input.ReadInt64();
            break;
          }
          case 24: {
            OfflineTtlInSeconds = input.ReadInt64();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            ProviderErrorStatus = input.ReadInt32();
            break;
          }
          case 16: {
            CacheTtlInSeconds = input.ReadInt64();
            break;
          }
          case 24: {
            OfflineTtlInSeconds = input.ReadInt64();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class EntityExtensionDataArray : pb::IMessage<EntityExtensionDataArray>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<EntityExtensionDataArray> _parser = new pb::MessageParser<EntityExtensionDataArray>(() => new EntityExtensionDataArray());
    private pb::UnknownFieldSet _unknownFields;
    private int _hasBits0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<EntityExtensionDataArray> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Spotify.Extendedmetadata.Proto.ExtendedMetadataReflection.Descriptor.MessageTypes[5]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public EntityExtensionDataArray() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public EntityExtensionDataArray(EntityExtensionDataArray other) : this() {
      _hasBits0 = other._hasBits0;
      header_ = other.header_ != null ? other.header_.Clone() : null;
      extensionKind_ = other.extensionKind_;
      extensionData_ = other.extensionData_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public EntityExtensionDataArray Clone() {
      return new EntityExtensionDataArray(this);
    }

    /// <summary>Field number for the "header" field.</summary>
    public const int HeaderFieldNumber = 1;
    private global::Spotify.Extendedmetadata.Proto.EntityExtensionDataArrayHeader header_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Spotify.Extendedmetadata.Proto.EntityExtensionDataArrayHeader Header {
      get { return header_; }
      set {
        header_ = value;
      }
    }

    /// <summary>Field number for the "extension_kind" field.</summary>
    public const int ExtensionKindFieldNumber = 2;
    private readonly static global::Spotify.Extendedmetadata.Proto.ExtensionKind ExtensionKindDefaultValue = global::Spotify.Extendedmetadata.Proto.ExtensionKind.UnknownExtension;

    private global::Spotify.Extendedmetadata.Proto.ExtensionKind extensionKind_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Spotify.Extendedmetadata.Proto.ExtensionKind ExtensionKind {
      get { if ((_hasBits0 & 1) != 0) { return extensionKind_; } else { return ExtensionKindDefaultValue; } }
      set {
        _hasBits0 |= 1;
        extensionKind_ = value;
      }
    }
    /// <summary>Gets whether the "extension_kind" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool HasExtensionKind {
      get { return (_hasBits0 & 1) != 0; }
    }
    /// <summary>Clears the value of the "extension_kind" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void ClearExtensionKind() {
      _hasBits0 &= ~1;
    }

    /// <summary>Field number for the "extension_data" field.</summary>
    public const int ExtensionDataFieldNumber = 3;
    private static readonly pb::FieldCodec<global::Spotify.Extendedmetadata.Proto.EntityExtensionData> _repeated_extensionData_codec
        = pb::FieldCodec.ForMessage(26, global::Spotify.Extendedmetadata.Proto.EntityExtensionData.Parser);
    private readonly pbc::RepeatedField<global::Spotify.Extendedmetadata.Proto.EntityExtensionData> extensionData_ = new pbc::RepeatedField<global::Spotify.Extendedmetadata.Proto.EntityExtensionData>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::Spotify.Extendedmetadata.Proto.EntityExtensionData> ExtensionData {
      get { return extensionData_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as EntityExtensionDataArray);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(EntityExtensionDataArray other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Header, other.Header)) return false;
      if (ExtensionKind != other.ExtensionKind) return false;
      if(!extensionData_.Equals(other.extensionData_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (header_ != null) hash ^= Header.GetHashCode();
      if (HasExtensionKind) hash ^= ExtensionKind.GetHashCode();
      hash ^= extensionData_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (header_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Header);
      }
      if (HasExtensionKind) {
        output.WriteRawTag(16);
        output.WriteEnum((int) ExtensionKind);
      }
      extensionData_.WriteTo(output, _repeated_extensionData_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (header_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Header);
      }
      if (HasExtensionKind) {
        output.WriteRawTag(16);
        output.WriteEnum((int) ExtensionKind);
      }
      extensionData_.WriteTo(ref output, _repeated_extensionData_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (header_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Header);
      }
      if (HasExtensionKind) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) ExtensionKind);
      }
      size += extensionData_.CalculateSize(_repeated_extensionData_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(EntityExtensionDataArray other) {
      if (other == null) {
        return;
      }
      if (other.header_ != null) {
        if (header_ == null) {
          Header = new global::Spotify.Extendedmetadata.Proto.EntityExtensionDataArrayHeader();
        }
        Header.MergeFrom(other.Header);
      }
      if (other.HasExtensionKind) {
        ExtensionKind = other.ExtensionKind;
      }
      extensionData_.Add(other.extensionData_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (header_ == null) {
              Header = new global::Spotify.Extendedmetadata.Proto.EntityExtensionDataArrayHeader();
            }
            input.ReadMessage(Header);
            break;
          }
          case 16: {
            ExtensionKind = (global::Spotify.Extendedmetadata.Proto.ExtensionKind) input.ReadEnum();
            break;
          }
          case 26: {
            extensionData_.AddEntriesFrom(input, _repeated_extensionData_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (header_ == null) {
              Header = new global::Spotify.Extendedmetadata.Proto.EntityExtensionDataArrayHeader();
            }
            input.ReadMessage(Header);
            break;
          }
          case 16: {
            ExtensionKind = (global::Spotify.Extendedmetadata.Proto.ExtensionKind) input.ReadEnum();
            break;
          }
          case 26: {
            extensionData_.AddEntriesFrom(ref input, _repeated_extensionData_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class BatchedExtensionResponseHeader : pb::IMessage<BatchedExtensionResponseHeader>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<BatchedExtensionResponseHeader> _parser = new pb::MessageParser<BatchedExtensionResponseHeader>(() => new BatchedExtensionResponseHeader());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<BatchedExtensionResponseHeader> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Spotify.Extendedmetadata.Proto.ExtendedMetadataReflection.Descriptor.MessageTypes[6]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public BatchedExtensionResponseHeader() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public BatchedExtensionResponseHeader(BatchedExtensionResponseHeader other) : this() {
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public BatchedExtensionResponseHeader Clone() {
      return new BatchedExtensionResponseHeader(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as BatchedExtensionResponseHeader);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(BatchedExtensionResponseHeader other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(BatchedExtensionResponseHeader other) {
      if (other == null) {
        return;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
        }
      }
    }
    #endif

  }

  public sealed partial class BatchedExtensionResponse : pb::IMessage<BatchedExtensionResponse>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<BatchedExtensionResponse> _parser = new pb::MessageParser<BatchedExtensionResponse>(() => new BatchedExtensionResponse());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<BatchedExtensionResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Spotify.Extendedmetadata.Proto.ExtendedMetadataReflection.Descriptor.MessageTypes[7]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public BatchedExtensionResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public BatchedExtensionResponse(BatchedExtensionResponse other) : this() {
      header_ = other.header_ != null ? other.header_.Clone() : null;
      extendedMetadata_ = other.extendedMetadata_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public BatchedExtensionResponse Clone() {
      return new BatchedExtensionResponse(this);
    }

    /// <summary>Field number for the "header" field.</summary>
    public const int HeaderFieldNumber = 1;
    private global::Spotify.Extendedmetadata.Proto.BatchedExtensionResponseHeader header_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Spotify.Extendedmetadata.Proto.BatchedExtensionResponseHeader Header {
      get { return header_; }
      set {
        header_ = value;
      }
    }

    /// <summary>Field number for the "extended_metadata" field.</summary>
    public const int ExtendedMetadataFieldNumber = 2;
    private static readonly pb::FieldCodec<global::Spotify.Extendedmetadata.Proto.EntityExtensionDataArray> _repeated_extendedMetadata_codec
        = pb::FieldCodec.ForMessage(18, global::Spotify.Extendedmetadata.Proto.EntityExtensionDataArray.Parser);
    private readonly pbc::RepeatedField<global::Spotify.Extendedmetadata.Proto.EntityExtensionDataArray> extendedMetadata_ = new pbc::RepeatedField<global::Spotify.Extendedmetadata.Proto.EntityExtensionDataArray>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::Spotify.Extendedmetadata.Proto.EntityExtensionDataArray> ExtendedMetadata {
      get { return extendedMetadata_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as BatchedExtensionResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(BatchedExtensionResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Header, other.Header)) return false;
      if(!extendedMetadata_.Equals(other.extendedMetadata_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (header_ != null) hash ^= Header.GetHashCode();
      hash ^= extendedMetadata_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (header_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Header);
      }
      extendedMetadata_.WriteTo(output, _repeated_extendedMetadata_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (header_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Header);
      }
      extendedMetadata_.WriteTo(ref output, _repeated_extendedMetadata_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (header_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Header);
      }
      size += extendedMetadata_.CalculateSize(_repeated_extendedMetadata_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(BatchedExtensionResponse other) {
      if (other == null) {
        return;
      }
      if (other.header_ != null) {
        if (header_ == null) {
          Header = new global::Spotify.Extendedmetadata.Proto.BatchedExtensionResponseHeader();
        }
        Header.MergeFrom(other.Header);
      }
      extendedMetadata_.Add(other.extendedMetadata_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (header_ == null) {
              Header = new global::Spotify.Extendedmetadata.Proto.BatchedExtensionResponseHeader();
            }
            input.ReadMessage(Header);
            break;
          }
          case 18: {
            extendedMetadata_.AddEntriesFrom(input, _repeated_extendedMetadata_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (header_ == null) {
              Header = new global::Spotify.Extendedmetadata.Proto.BatchedExtensionResponseHeader();
            }
            input.ReadMessage(Header);
            break;
          }
          case 18: {
            extendedMetadata_.AddEntriesFrom(ref input, _repeated_extendedMetadata_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
